version: "3"

services:
  wgm_database:
    image: postgres:14
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wgm
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - wgm_database

  wgm_server:
    build: ./server
    tty: true
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - wgm_database
    networks:
      - default
