version: "3"

services:
  db:
    image: postgres:14
    restart: always
    tty: true
    container_name: wgm_database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=wgm
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db